# Generated by Django 3.0.5 on 2020-05-09 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200509_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Avatar'),
        ),
    ]
