# Generated by Django 3.0.5 on 2020-05-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200509_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='piew',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/'),
        ),
    ]
