# Generated by Django 3.0.5 on 2020-05-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_piew_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piew',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
